-- Seed data for public.topics — Levelpath Gen AI learning plan
-- 23 topics across 3 phases. id and created_at are left for the database to generate.

INSERT INTO public.topics
  (phase, title, is_mandatory, effort_hours, key_terms, learning_outcomes, video_url, practice_url, additional_resources, sort_order)
VALUES

-- ===== PHASE 1 (8 topics) =====

(1, 'Introduction to LLMs', true, 0.5,
 'AI, Machine Learning, LLM, LLM Models Available (GPT, Claude..)',
 'Explain what an LLM is, the difference between proprietary and open-source models, and which model fits which use case.',
 'https://youtu.be/vf_mZrn8ibc?si=jS0XDZZ8Ljz8jTn4',
 'https://colab.research.google.com/github/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/chapter01/Chapter%201%20-%20Introduction%20to%20Language%20Models.ipynb',
 'https://github.com/HandsOnLLM/Hands-On-Large-Language-Models',
 1),

(1, 'Tokens & Tokenization', true, 0.5,
 'Tokens, BPE, vocabulary, context window',
 'Explain how text becomes tokens, why context windows matter, and estimate token cost of a prompt.',
 'https://youtu.be/r17HV0TzAWw?t=1',
 'https://platform.openai.com/tokenizer',
 'https://tiktokenizer.vercel.app/',
 2),

(1, 'Prompt Engineering', true, 2.5,
 'Zero-shot, one-shot, instruction prompting, role prompts, Chain-of-thought, few-shot, self-consistency, ReAct, prompt chaining',
 'Write a clear prompt with role, task, context, format, and constraints. Pick the right technique for a task and chain prompts for multi-step problems.',
 'https://youtu.be/uDIW34h8cmM?si=KO7S7P1bGH0ss22L',
 'https://www.promptingguide.ai/techniques',
 'https://learnprompting.org/docs/intro',
 3),

(1, 'Hallucinations & Reliability', true, 0.5,
 'Hallucinations, grounding, factuality, calibration',
 'Identify when a model is likely to hallucinate, design prompts that reduce hallucination, and verify model output.',
 'https://youtu.be/odQO6MmNzBw?si=oM7kwXUw93S-nxro',
 'https://www.youtube.com/watch?v=odQO6MmNzBw',
 NULL,
 4),

(1, 'LLM Parameters', true, 2.0,
 'Temperature, Top-p, Top-k, Max tokens, Stop sequence, Deterministic output',
 'Explain what temperature controls and when to set it high vs low. Choose the right parameters for a creative vs a factual task.',
 'https://youtu.be/uDIW34h8cmM?si=KO7S7P1bGH0ss22L',
 NULL,
 'Run the same prompt at temperature 0, 0.5, and 1.0 and compare outputs.',
 5),

(1, 'Embeddings', true, 2.0,
 'Embedding, Vector, Semantic similarity, Cosine similarity, Embedding model',
 'Explain what an embedding is in plain English. Describe why embeddings are useful for search. Run a simple embedding similarity example in Python.',
 'https://cohere.com/llmu',
 'https://colab.research.google.com/github/cohere-ai/cohere-developer-experience/blob/main/notebooks/llmu/Introduction_Text_Embeddings.ipynb',
 'https://cohere.com/llmu',
 6),

(1, 'Responsible AI', false, 1.5,
 'Bias, fairness, transparency, safe use, privacy, attribution',
 'Recognize bias and harm risks in LLM outputs, follow safe-use guidelines, and decide when an LLM should NOT be used.',
 'https://learn.microsoft.com/en-us/training/modules/embrace-responsible-ai-principles-practices/',
 'https://learn.microsoft.com/en-us/training/paths/responsible-ai-business-principles/',
 'https://www.nist.gov/itl/ai-risk-management-framework',
 7),

(1, 'Advanced Topics', false, 1.0,
 'Transformer, Fine-tuning, RLHF',
 'Explain at a high level what a transformer is, what fine-tuning does, and how RLHF shapes assistant behavior.',
 'https://youtu.be/wjZofJX0v4M?si=UDaxHNKevq3LTDZy',
 NULL,
 'https://colab.research.google.com/drive/1JMLa53HDuA-i7ZBmqV7ZnA3c_fvtXnx-?usp=sharing',
 8),

-- ===== PHASE 2 (7 topics) =====

(2, 'AI Agents', true, 0.5,
 'Agents, Tools and its use, Internal Agent calls, Agentic Frameworks, LangGraph, CrewAI',
 'Explain the difference between a genAI and an agentic AI. Trace through a reasoning loop step by step. Decide when a task needs an agent vs a simple LLM call.',
 'https://youtu.be/FwOTs4UxQS4?si=YuK9tKlRwKx1Zcog',
 'https://blogs.nvidia.com/blog/what-is-agentic-ai/',
 'https://github.com/NirDiamant/GenAI_Agents',
 1),

(2, 'LangChain Basics', true, 2.0,
 'LangChain, Chain, Prompt template, Output parser, Runnable, RunnableSequence',
 'Set up a LangChain project and connect it to an LLM. Build a simple 3-step chain using LCEL syntax. Use an output parser to extract structured data from LLM responses.',
 'https://youtu.be/nAmC7SoVLd8?si=oIU08Y-mq6DIdhHO',
 'https://github.com/langchain-ai/langchain-academy',
 'https://academy.langchain.com/courses/foundation-introduction-to-langchain-python',
 2),

(2, 'LangChain Tool Use & Function Calling', true, 1.0,
 'Tool, Function calling, JSON schema, Tool selection, Tool result, Custom tool',
 'Define a custom tool with a proper description and input schema. Build an agent that picks the right tool from a set of 3+. Handle a tool error gracefully inside the agent loop.',
 'https://youtu.be/zCwuAlpQKTM?si=HD0vdQkHTKfoMD2_',
 'https://academy.langchain.com/courses/foundation-introduction-to-langchain-python',
 'https://academy.langchain.com/courses/foundation-introduction-to-langchain-python',
 3),

(2, 'LangChain Memory in Agents', true, 1.0,
 'Conversation memory, Buffer memory, Summary memory, Vector memory, Context compression',
 'Add conversation buffer memory to a chatbot chain. Switch to summary memory for long conversations. Choose the right memory type for a given use case.',
 'https://youtu.be/UXGNpuHgT5g?si=hSa-ZZAI5H3-hQDK',
 'https://academy.langchain.com/courses/foundation-introduction-to-langchain-python',
 'https://academy.langchain.com/courses/foundation-introduction-to-langchain-python',
 4),

(2, 'LangGraph — Single & Multi-agent Systems', true, 3.0,
 'LangGraph, StateGraph, Node, Edge, Conditional edge, State schema, Checkpointers',
 'Create a StateGraph with at least 3 nodes and a conditional edge. Define a proper state schema for a workflow. Add checkpointing so a workflow can be paused and resumed.',
 'https://youtube.com/playlist?list=PLfaIDFEXuae16n2TWUkKq5PgJ0w6Pkwtg',
 'https://github.com/langchain-ai/langchain-academy',
 'https://academy.langchain.com/courses/intro-to-langgraph',
 5),

(2, 'Human-in-the-Loop', true, 0.5,
 'Interrupt, Approval step, Human review, Resume, Breakpoint',
 'Add a human approval step inside a LangGraph workflow. Pause a graph mid-execution and resume it after human input. Explain when you would want human-in-the-loop vs full automation.',
 'https://youtube.com/playlist?list=PLfaIDFEXuae16n2TWUkKq5PgJ0w6Pkwtg',
 'https://academy.langchain.com/courses/intro-to-langgraph',
 'https://academy.langchain.com/courses/intro-to-langgraph',
 6),

(2, 'Multi-agent Systems with CrewAI', false, 3.0,
 'CrewAI, Multi-agent, Orchestrator, Subagent, Role, Task delegation, Handoff',
 'Design a crew of 3 agents with distinct roles for a content task. Pass output from one agent as input to another. Debug a breakdown in a multi-agent handoff.',
 'https://www.youtube.com/playlist?list=PL9n0l8rSshSmLOaCHKzhuLKjbesCP5yXi',
 'https://github.com/NirDiamant/GenAI_Agents',
 'https://docs.crewai.com',
 7),

-- ===== PHASE 3 (8 topics) =====

(3, 'RAG — Build a Knowledge Pipeline', true, 2.0,
 'RAG, Chunking, Embedding, Vector DB, Retriever',
 'Build an end-to-end indexing pipeline: load docs, chunk, embed, store. Retrieve relevant chunks for a query and feed them into an LLM prompt. Explain the different chunk strategies.',
 'https://youtu.be/4Ax77tnW0e8',
 'https://github.com/NirDiamant/RAG_Techniques',
 'https://blogs.nvidia.com/blog/what-is-retrieval-augmented-generation/',
 1),

(3, 'Security & Safety', true, 1.0,
 'Prompt injection, Input validation, Output sanitisation, PII detection, API key rotation',
 'Identify a prompt injection attempt and explain how to block it. Add input validation and output sanitisation to an LLM endpoint. Set up safe API key management.',
 'https://youtu.be/X9oLeT86GBE?si=ErV_6_oN5WQrwelF',
 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
 2),

(3, 'Responsible AI — Applied', true, 1.5,
 'Red-teaming, Harm taxonomies, Guardrails, Llama Guard, NeMo Guardrails, Bias & fairness eval, Model cards',
 'Run a red-team test plan against an agent. Design adversarial prompts, measure failure rate, and add guardrails to mitigate. Explain how Responsible AI requirements differ for an agent vs a plain chatbot.',
 'https://www.youtube.com/watch?v=Wo95ob_s_NI',
 'https://github.com/meta-llama/PurpleLlama',
 'https://github.com/meta-llama/PurpleLlama',
 3),

(3, 'MCP — Model Context Protocol', true, 3.0,
 'MCP, MCP server, MCP client, Tool registration, Resource, Claude Desktop, Claude Code',
 'Explain MCP architecture: what a host, client, and server each do. Connect Claude to an existing MCP server and test it. Build a custom MCP server that exposes 2 tools.',
 'https://youtu.be/E2DEHOEbzks?t=5',
 'https://docs.anthropic.com/en/docs/build-with-claude/mcp',
 'https://github.com/modelcontextprotocol/python-sdk',
 4),

(3, 'Production Patterns & Reliability', true, 1.0,
 'Retry logic, Fallback, Timeout, Rate limiting, Caching, Cost tracking, Guardrails',
 'Add retry with exponential backoff to an agent tool call. Set up output guardrails to catch harmful or off-topic responses. Track token usage and cost per request in a production flow.',
 'https://youtu.be/i13aUgp9rcY?si=hdBQBY5jQU149pLb',
 'https://github.com/NirDiamant/agents-towards-production',
 'https://github.com/NirDiamant/agents-towards-production',
 5),

(3, 'Deployment', true, 1.0,
 'FastAPI, Docker, Containerisation, Environment config, Health check, CI/CD',
 'Wrap a GenAI app in a FastAPI endpoint with proper error handling. Dockerise the app and run it in a container locally. Describe how you would promote it from dev to staging to prod.',
 'https://youtu.be/Y9YbCvzAwas?t=2',
 'https://fastapi.tiangolo.com',
 'https://fastapi.tiangolo.com',
 6),

(3, 'Observability', false, 2.0,
 'Langfuse, Langsmith, AWS GenAI observability, Trace, Evaluation frameworks, deepeval, Evaluations using Datasets',
 'Read a trace to understand where an agent went wrong. Create a small eval dataset and run it against a prompt in Langfuse or any third-party framework.',
 'https://youtu.be/otY2_M_pTmU?t=383',
 'https://langfuse.com/watch-demo',
 'https://academy.langchain.com/courses/intro-to-langsmith',
 7),

(3, 'RAG — Improve Retrieval Quality', false, 1.0,
 'Hybrid search, Re-ranking, Multi-query retrieval, Self-RAG, RAGAS, Faithfulness',
 'Implement hybrid search (keyword + semantic) on a vector store. Add a cross-encoder re-ranker to improve result precision. Evaluate your RAG pipeline using RAGAS and interpret the scores.',
 'https://www.youtube.com/live/kOALKZvhMgQ?si=09S3MEHU7ct5XVMh',
 'https://github.com/NirDiamant/RAG_Techniques',
 'https://github.com/NirDiamant/RAG_Techniques',
 8);
